export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const CREATE_IMAGE = 'CREATE_IMAGE';
export const CREATE_ARTWORK = 'CREATE_ARTWORK';
export const CLASSIFY_IMAGE = 'CLASSIFY_IMAGE';
export const CREATE_TAGS = 'CREATE_TAGS';
export const REJECT_TAG = 'REJECT_TAG';
export const EXPLORE_BASED_ON_THIS_ARTWORK = 'EXPLORE_BASED_ON_THIS_ARTWORK';
