export const NAV_ITEM_CLICKED = 'NAV_ITEM_CLICKED';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const CHECK_LOGGED_IN = 'CHECK_LOGGED_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_LOCATION = 'GET_LOCATION';