export const TAKE_SUGGESTION = 'TAKE_SUGGESTION';
export const UNDO_TAKE_SUGGESTION = 'UNDO_TAKE_SUGGESTION';
export const MORE_SUGGESTIONS_LIKE_THIS = 'MORE_SUGGESTIONS_LIKE_THIS';
export const SHOW_SUGGESTION = 'SHOW_SUGGESTION';
export const HIDE_SUGGESTION = 'HIDE_SUGGESTION';
export const SHOW_QUEST = 'SHOW_QUEST';