export const HIDE_MEANING_GROUP = 'HIDE_MEANING_GROUP';
export const SHOW_MEANING_GROUP = 'SHOW_MEANING_GROUP';
export const DISPLAY_MATCHING_QUEST = 'DISPLAY_MATCHING_QUEST';
export const DISMISS_MATCHING_QUEST = 'DISMISS_MATCHING_QUEST';
export const CONFIRM_MATCHING_QUEST = 'CONFIRM_MATCHING_QUEST';